name: action-server-do-example2

services:
  - name: action-server
    dockerfile_path: ./deploy-digital-ocean/docker/Dockerfile
    git:
      branch: master
      repo_clone_url: https://github.com/29decibel/actions-cookbook.git
    source_dir: deploy-digital-ocean
    routes:
      - path: /
    envs:
      - key: ACTION_SERVER_URL
        value: "https://action-server-do-example2-d37pj.ondigitalocean.app"
      - key: ACTION_SERVER_KEY
        value: "nicetomeetyou"
        type: SECRET
